import React from 'react';
import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import { useDispatch, useSelector } from 'react-redux';
import { openSidenavAction, closeSidenavAction } from '@/store/modules/sidenav';
import styles from '../styles/Home.module.scss';
import { IStore } from '@/store/modules';

const Home: NextPage = () => {
  const dispatch = useDispatch();
  const openSidenavDispatch = () => dispatch(openSidenavAction());
  const closeSidenavDispatch = () => dispatch(closeSidenavAction());
  const selectedSideNav = useSelector((state: IStore) => state.sidenav.isActive);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div>
          {selectedSideNav && 'Sidenav is active'}
          <button type="button" onClick={openSidenavDispatch}>
            open side nav
          </button>
          <button type="button" onClick={closeSidenavDispatch}>
            close side nav
          </button>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
};

export default Home;
